# Generated by Django 5.1.1 on 2024-10-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='specialization',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
