# Generated by Django 5.1.1 on 2024-10-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_teamjobseeker_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamjoinrequest',
            name='message',
        ),
    ]
