# Generated by Django 4.1.6 on 2024-09-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='founded_date',
        ),
    ]
