# Generated by Django 5.1.1 on 2024-09-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_company_founded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='employer_type',
        ),
    ]
