# Generated by Django 5.1.1 on 2024-09-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_individualemployerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualemployerprofile',
            name='is_admin',
        ),
    ]
