# Generated by Django 5.1.1 on 2024-09-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_individualemployerprofile_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='pcreated_at',
            new_name='created_at',
        ),
    ]
