# Generated by Django 5.1.1 on 2024-09-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_pcreated_at_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_company_employer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='individualemployerprofile',
            name='is_individual',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
