# Generated by Django 5.1.1 on 2024-09-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_employerprofile_is_company_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualemployerprofile',
            name='is_individual',
        ),
        migrations.AddField(
            model_name='individualemployerprofile',
            name='is_individual_employer',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='is_company_employer',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
