# Generated by Django 5.1.1 on 2024-11-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_jobseekerprofile_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='university',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='school_or_university',
            field=models.CharField(blank=True, choices=[('UPNG', 'University of Papua New Guinea (UPNG)'), ('UNITECH', 'Papua New Guinea University of Technology (UNITECH)'), ('UOG', 'University of Goroka (UOG)'), ('UNRE', 'University of Natural Resources and Environment (UNRE)'), ('WPU', 'Western Pacific University (WPU)'), ('DWU', 'Divine Word University (DWU)'), ('PAU', 'Pacific Adventist University (PAU)'), ('IBS', 'Institute of Business Studies (IBS) University'), ('LTI', 'Legal Training Institute (LTI)'), ('PNGMC', 'PNG Maritime College'), ('MAPEX', 'Mapex Training Institute'), ('MadangTC', "Madang Teachers' College"), ('HolyTrinityTC', "Holy Trinity Teachers' College"), ('StBenedictsTC', "St. Benedict’s Teachers' College"), ('BalobTC', "Balob Teachers' College"), ('LaeSN', 'Lae School of Nursing'), ('MadangLSN', 'Madang Lutheran School of Nursing'), ('StBarnabasSN', 'St. Barnabas School of Nursing'), ('MendiSN', 'Mendi School of Nursing'), ('KudjipNCN', 'Kudjip Nazarene College of Nursing'), ('DBTI', 'Don Bosco Technical Institute'), ('POMTech', 'Port Moresby Technical College'), ('LaeTech', 'Lae Technical College'), ('GorokaTech', 'Goroka Technical College'), ('MtHagenTech', 'Mt. Hagen Technical College'), ('PNGIMR', 'PNG Institute of Medical Research')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='province',
            field=models.CharField(blank=True, choices=[('NCD', 'National Capital District'), ('Central', 'Central Province'), ('Milne Bay', 'Milne Bay Province'), ('Oro', 'Oro Province'), ('Western', 'Western Province'), ('Gulf', 'Gulf Province'), ('Morobe', 'Morobe Province'), ('Madang', 'Madang Province'), ('East Sepik', 'East Sepik Province'), ('West Sepik', 'West Sepik (Sandaun) Province'), ('Enga', 'Enga Province'), ('Southern Highlands', 'Southern Highlands Province'), ('Hela', 'Hela Province'), ('Western Highlands', 'Western Highlands Province'), ('Jiwaka', 'Jiwaka Province'), ('Eastern Highlands', 'Eastern Highlands Province'), ('Simbu', 'Simbu Province'), ('Bougainville', 'Autonomous Region of Bougainville'), ('East New Britain', 'East New Britain Province'), ('West New Britain', 'West New Britain Province'), ('New Ireland', 'New Ireland Province'), ('Manus', 'Manus Province')], max_length=50, null=True),
        ),
    ]
