# Generated by Django 5.1.1 on 2024-11-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_jobseekerprofile_university_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GeneralExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('referer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('referer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='profiles.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.jobseekerprofile')),
            ],
        ),
    ]
