# Generated by Django 5.1.1 on 2024-11-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_jobseekerprofile_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='generalexperience',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='generalexperience',
            name='start_date',
        ),
    ]
