# Generated by Django 5.1.1 on 2024-11-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_generalexperience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='carrier',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
