# Generated by Django 5.1.1 on 2024-09-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='apply_link',
        ),
    ]
