# Generated by Django 5.1.1 on 2024-10-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0007_remove_jobposting_remote_jobposting_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='industry',
            field=models.CharField(choices=[('healthcare', 'Healthcare - Hospitals, Clinics, Pharmaceuticals'), ('information-technology', 'Information Technology - Software, IT Services, Cybersecurity'), ('finance', 'Finance - Banking, Investment, Insurance'), ('education', 'Education - Schools, Universities, Online Learning'), ('manufacturing', 'Manufacturing - Automotive, Electronics, Food Production'), ('construction', 'Construction - Residential, Commercial, Infrastructure'), ('retail', 'Retail - E-commerce, Fashion, Grocery Stores'), ('hospitality', 'Hospitality - Hotels, Restaurants, Tourism'), ('marketing-and-advertising', 'Marketing and Advertising - PR, Digital Marketing, Branding'), ('telecommunications', 'Telecommunications - Network Services, Mobile, Satellite'), ('transportation-and-logistics', 'Transportation and Logistics - Shipping, Supply Chain, Public Transit'), ('energy-and-utilities', 'Energy and Utilities - Oil and Gas, Renewable Energy, Water Supply'), ('real-estate', 'Real Estate - Residential Sales, Commercial Leasing, Property Management'), ('government-and-public-administration', 'Government and Public Administration - Local, Federal, Military'), ('legal-services', 'Legal Services - Law Firms, Compliance, Corporate Counsel'), ('media-and-entertainment', 'Media and Entertainment - Film, TV, Publishing, Gaming'), ('agriculture', 'Agriculture - Farming, Animal Husbandry, Food Processing'), ('non-profit-and-ngos', 'Non-Profit and NGOs - Charity, Advocacy, International Development'), ('science-and-research', 'Science and Research - Academic, Clinical Trials, Private Labs'), ('human-resources', 'Human Resources - Recruitment, Employee Relations, Training')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(choices=[('central', 'Central'), ('gulf', 'Gulf'), ('oro', 'Oro'), ('southern-highlands', 'Southern Highlands'), ('hela', 'Hela'), ('western-highlands', 'Western Highlands'), ('enga', 'Enga'), ('east-sepik', 'East Sepik'), ('west-sepik', 'West Sepik (Sandaun)'), ('madang', 'Madang'), ('morobe', 'Morobe'), ('new-ireland', 'New Ireland'), ('east-new-britain', 'East New Britain'), ('west-new-britain', 'West New Britain'), ('bougainville', 'Bougainville'), ('milne-bay', 'Milne Bay'), ('northern', 'Northern'), ('chimbu', 'Chimbu (Simbu)'), ('jiwaka', 'Jiwaka'), ('western', 'Western'), ('national-capital-district', 'National Capital District')], max_length=50),
        ),
    ]
