# Generated by Django 5.1.1 on 2024-10-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0009_savejobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='saveJobs',
        ),
    ]
