# Generated by Django 5.1.1 on 2024-09-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_employernotification_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekernotification',
            name='application_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekernotification',
            name='application_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
