# Generated by Django 5.1.1 on 2024-10-04 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_jobseekernotification_application_accepted_and_more'),
        ('teams', '0006_remove_teamjoinrequest_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamJoinRequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_team_request', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_request', to='teams.team')),
                ('team_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_team_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
