# Generated by Django 5.1.1 on 2024-10-04 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_teamjoinrequestnotification'),
        ('teams', '0006_remove_teamjoinrequest_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamjoinrequestnotification',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_request_notifications', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='teamjoinrequestnotification',
            name='team_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_team_requests_notifictions', to=settings.AUTH_USER_MODEL),
        ),
    ]
