# Generated by Django 5.1.1 on 2024-10-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_teamjoinrequestnotification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamjoinrequestnotification',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
