# Generated by Django 5.1.1 on 2024-10-04 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_teamjoinrequestnotification_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamjoinrequestnotification',
            name='is_for_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teamjoinrequestnotification',
            name='is_for_requester',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teamjoinrequestnotification',
            name='team_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_team_requests_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
