# Generated by Django 5.1.1 on 2024-10-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_teamjoinrequestnotification_is_for_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamjoinrequestnotification',
            old_name='team_admin',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='teamjoinrequestnotification',
            name='requester',
        ),
    ]
