# Generated by Django 5.1.1 on 2025-04-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_rename_team_admin_teamjoinrequestnotification_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeekerNotification',
        ),
    ]
