# Generated by Django 5.1.1 on 2025-04-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_remove_jobpostingnotification_applicant'),
        ('profiles', '0014_jobseekerprofile_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingnotification',
            name='jobseeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_notifications_job', to='profiles.jobseekerprofile'),
        ),
    ]
